### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#18]
please can we have 

 1)  a health drop down menu on right side but call it "Physical Activity Benefits - To be Completed"
2) On the top can we have a tab saying - "View Results as a Table- To be Completed"

Robin - I think this what we agreed - please say if not

j.

**Comment by Robinlovelace** [comment]
@nikolai-b any progress on this? At present it seems the tab menus aren't quite set-up right and map doesn't load as default - this is what I see: 
![selection_172](https://cloud.githubusercontent.com/assets/1825120/7105416/ad4611a2-e10e-11e4-87fc-b35f3ebf8096.png)

**Comment by nikolai-b** [comment]
Thanks @Robinlovelace, that was a mistake when I added the google analytics fixed in 871dd1bc8c5519ece4cd5b76b75cfa1f2c3cbb90 .
Ideally new features would be added to the Trello board and prioritized.  I've not made progress on this yet, can it be given a priority compared to other new things needed?

**Comment by Robinlovelace** [comment]
Not high priority - will look at Trello.
Adding an empty tab should be pretty easy though right?

**Comment by nikolai-b** [comment]
Moved to https://trello.com/c/ulz8ObKc/14-3h-add-tabs
