### ISSUE TITLE
Create script or function to aggregate OD data for small areas

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#291]
This involves
- [ ] convert data into SpatialLines
- [ ] finding a way to classify zones that are small, e.g.:

``` r
is_small = function(x, min_area, min_length){
  rgeos::gArea(x, by.id = T) < min_area |
    lakemorpho::lakeMaxWidth(x_lakemorpho) < min_length)
```
- [ ] aggregate the SpatialLines in areas that are small

**Comment by audev** [comment]
Thanks for intro @Robinlovelace.  Still a bit of context needed. 

Let me put it as I understand it:

1. We are moving PCT to LSOA level for all sources (OD flows, linked geographic files, centroids, etc).
2. You plan to classify LSOA zones into groups (small/large,..), based on certain criteria (max. length, area, etc).
3. Flows between small LSOAs will be added. Then only 1 line shown for the group of LSOAs. 

Is this right?

Questions:

- Which flows will then qualify for aggregation (e.g. 1 small orig LSOA -> 3 small LSOA destinations, that are contiguous)? Otherwise not clear.
- I take step1 -convert data into SpatialLines just means using your package to put the flow file into the standard spatial format? Not sure if you're talking here about the raw Census file or the [pct_lines_oneway_shapes.Rds]  ?

**Comment by Robinlovelace** [comment]
- We are moving PCT to LSOA level for all sources (OD flows, linked geographic files, centroids, etc).

Yes we are planning to create a new version of the PCT using LSOA data.

- You plan to classify LSOA zones into groups (small/large,..), based on certain criteria (max. length, area, etc).

Yes, potentially using a helper function such as `is_small()` sketched above.

- Flows between small LSOAs will be added. Then only 1 line shown for the group of LSOAs.  Is this right?

Yes.


Questions:

- Which flows will then qualify for aggregation (e.g. 1 small orig LSOA -> 3 small LSOA destinations, that are contiguous)? Otherwise not clear.

The task is to develop a method that can answer that question. It depends on the implementation. It may be worth creating a couple of implementations, or passing argument values to the function that will determine how it answers that question.

- I take step1 -convert data into SpatialLines just means using your package to put the flow file into the standard spatial format? Not sure if you're talking here about the raw Census file or the [pct_lines_oneway_shapes.Rds]  ?

It's up to the person who develops this to decide how best to convert the non geographical data into geographical data but yes, I would suggest using the functionality provided by **stplanr** to do this work.

**Comment by Robinlovelace** [comment]
@audev furthermore, please could you use repo to develop test code and upload test data for the lsoa work: https://github.com/npct/pct-lsoa-test - Just given you push access I think - let me know if not.

**Comment by Robinlovelace** [comment]
Closing as not working on it - partly duplicated by this, where I think this function should live: https://github.com/ropensci/stplanr/issues/152
