### ISSUE TITLE
Complete model output tab

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#299]
- [x] Update graphics
- [ ] Add new summary table
- [ ] Include summary of health and CO2 savings

**Comment by AnnaGoodman1** [comment]
also need to correct the number given where it states the between zone number of lines in the first section, at the moment it seems to be adding together the between zone and within zone number of lines

**Comment by AnnaGoodman1** [comment]
[160810_Model output.docx](https://github.com/npct/pct-shiny/files/411140/160810_Model.output.docx)

template for tables

**Comment by AnnaGoodman1** [comment]
a further issue is that we need to look up table that goes from our internal region name to the region name as you want it to appear on the screen.  The current syntax only works for regions with the single word is the name.  otherwise we get sentences like "there were 1,124,157 commuters living in Greater-manchester recorded in the 2011 Census."

**Comment by Robinlovelace** [comment]
Thanks Anna, this is a good point. @usr110 in case it helps, I already wrote code to fix this issue here: https://github.com/npct/pct-shiny/blob/master/scripts/mapgen.R#L24

**Comment by AnnaGoodman1** [comment]
now complete!
