### ISSUE TITLE
Finalise user manual

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#301]
Also links to training materials.

**Comment by Robinlovelace** [comment]
By building on this - let me know if there any issues with writing in .Rmd format - that's the preference as it reduces time translating from docx to .Rmd, but happy to do so if needs be.

Latest version:

https://github.com/npct/pct-shiny/edit/master/static/manual.Rmd

**Comment by usr110** [comment]
The manual needs updating. Specifically `How should the tool be used?` section where not only the text, but the screen grabs are quite old - and/or are not applicable any more. 
Overall all the text and screenshots need to be updated.
In addition to that: all links should open in a new tab; this goes for all figures too.

**Comment by Robinlovelace** [comment]
Agreed. @RachelAldred has created an updated version I believe which needs to be ported into https://github.com/npct/pct-shiny/blob/master/static/manual.Rmd at some point.

**Comment by Robinlovelace** [comment]
Prioritised because there's out of date information (e.g. images) in there. The images can be updated here: https://github.com/npct/pct-shiny/tree/master/www/img/help

**Comment by RachelAldred** [comment]
Just was looking for one of the images to use in a case study and it's true that none of them are there - so in the short term putting the images back is a priority I think, particularly for sections 2-4, because that methods-related material's quite hard to understand without them.

In terms of the manual, I will as discussed be writing it in Dropbox on Word. The deadline for writing this material is 30th September - in draft form.

**Comment by usr110** [comment]
@RachelAldred The (outdatad) images are available on the [test-server](http://npct0.vs.mythic-beasts.com/manual.html)

**Comment by JDWoodcock** [comment]
Just to confirm it was agreed that this we will be in Word as agreed and will be for the end of the Sept. It does not need to go into .rmd as it a static document.

**Comment by Robinlovelace** [comment]
Think this is done - thanks @RachelAldred
