### ISSUE TITLE
Route data in rds format have missing variables

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#343]
The missing columns of distances (among many other variables) are joined from the lines object `l.Rds` to the fast-route `rf.Rds` and quiet-route `rq.Rds` objects _within_ pct-shiny, hence users are unable to see them when they download the unprocessed objects. See the code [here](https://github.com/npct/pct-shiny/blob/master/server-base.R#L64-L67):

For instance: these are columns present in the two rds files:

> colnames(readRDS("../pct-data/cambridgeshire/rf.Rds")@data)
[1] "length"      "time"        "change_elev" "av_incline"  "id"   

> colnames(readRDS("../pct-data/cambridgeshire/rq.Rds")@data)
[1] "length"      "time"        "change_elev" "av_incline"  "id"   

I propose two solutions for it:
1) Supply processed objects to users (with distance variables such as `dist_quiet` and `dist_fast`)
2) Create fully processed `fast `and `quiet `objects with all the missing columns using `pct-load` (as we have discussed a few times earlier)

I am personally in favour of the second option. What do you guys @npct/admin think?

**Comment by Robinlovelace** [comment]
I agree with option 2.

**Comment by Robinlovelace** [comment]
If that's the case, the *action* associated with this issue is the following:

**Update the user manual to explain how to join l.csv data with rf and rq .geojson/.Rds files.**

Happy to help with this, suggest @RachelAldred leads.

**Comment by usr110** [comment]
@Robinlovelace I disagree with you here. The whole exercise of providing data to users is to help them as much as possible. It will be too much to ask them to join the data themselves.
If you would like to talk about simplify, then, in my view, these columns like `dist_quiet` and `dist_fast` shouldn't really exist in `l.rds` object. 
Drastic solution (may be for more discussion in the future): create just one object which has all lines, quiet and fast data. There is no need to have three separate objects. This will resolve the issue of repetitive columns and also reduce the size of the `pct-data` repository. What do you think @nikolai-b?

**Comment by AnnaGoodman1** [comment]
My initial suggestion when we were looking to improve the data download was to a) present a CSV file + codebook on its own line as an 'attributes file' with all scenario and geographic data in it, and b) present fast route/quiet route geographic files that only contained shape information, no line attributes (i.e. they would not need a code book) that users could merge into.  Robin and Nikolai overruled that at the time but I still think both ideas might be helpful, as at present it is less obvious where the scenario data is, and confusing to have just a few variables in rf/rq (with NB some units  difference from l.csv - also confusing - and with differences in the names).  The user manual helps, but I think we want it as intuitive as possible on the screen too.

Another option that I like even better would be to do the join ourselves very downstream into the fast route and quiet files, so that all three of the lines formats contain the same set of scenario numbers - so I think I'm on Ali's side for that if I have understood the suggestion right.  If done at the last minute then I don't see a great risk of DRY.

( If possible to have a single object that could do all three that could also be good - don't understand the details)

**Comment by nikolai-b** [comment]
In this case we should do the download on-the-fly in shiny.

I've made a start in https://github.com/npct/pct-shiny/tree/download_on_fly what do you think @usr110 and @Robinlovelace ?  This has an issue that the geojson files will be massive (30Mb or more....) and we can't simplify on the fly (ms_simplify is too slow) but we can rename and join e.t.c.

**Comment by nikolai-b** [comment]
From the call this morning it seems @Robinlovelace and @usr110 were not happy with the idea of doing this on the server.  Without simplification rf is ~12Mb for a geojson download but it takes almost no processing power.  For what it is worth I'm with @AnnaGoodman1 that we should join this ourselves and not ask users to.

Without allowing data to be downloaded from the shiny app I cannot see a way of progressing without doing a new national build...

**Comment by Robinlovelace** [comment]
There's an update on this: merging is no longer necessary as the scenarios and route network data are now very separate entities (one was not used to create the other).

Therefore the latest solution, based on discussion this morning and the utility of new hilliness data for decision makers and our own analysis, as flagged by @RachelAldred is to make clear that they are different from the scenarios and in the manual.

This is what we're doing already so closing the issue for now.

Suggest it's re-opened as and when there's a clear action that we agree on (probably when the new complete route data is in during September).

Productive discussion in any case, looking forward to the new data from CycleStreets.net cc @mvl22.
