### ISSUE TITLE
Hard to read zones visualisation of cycle commuting %s / colour scale inconsistency issue

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#344]
I am still not convinced by showing %s instead of absolute numbers for zones. What do others think? It is not immediately clear to me which each represents and the greens all look the same (maybe this is my eyes!). So at least a colour tweak might help. Screenshot below.

![kentpic](https://cloud.githubusercontent.com/assets/11818218/17513749/a96045da-5e26-11e6-93fa-d679e1831e37.jpg)

**Comment by Robinlovelace** [comment]
Agreed a color tweak could be good. Not a priority so marked as a discussion. Suggest we focus on priority issues 'till after August 25th. Great to be thinking about these things. I'm definitely in favour of the new % legend that @nikolai-b created FWIW.

**Comment by AnnaGoodman1** [comment]
.I am also in favour of showing percentages, I think the problem with the colours is not about percentages versus absolute numbers but about whether you have a fixed scale across all scenarios.  I agree with Rachel that what we have at the moment doesn't really work for this, and given that ebikes often have 10 times higher cycling I'm not sure we will ever find a colour scale that covers the full range well enough.  It is worth exploring whether this is possible, otherwise I suggest we should keep percentages but return to having a floating scale for each scenario.

I also think it would be good to fix this before 25th August if possible, though not a priority in the next couple of days.

**Comment by Robinlovelace** [comment]
:+1: thanks Anna, agreed.

**Comment by AnnaGoodman1** [comment]
If we do explore an expanded/modified colour scale, I think it would be really good to try to harmonise it with the front page (either one way or the other). At the moment, the two scales are inconsistent, with green meaning "better than yellow" on the homepage but "worse than yellow" once you're  in a region.

**Comment by nikolai-b** [comment]
I agree that the map on the front page should match the map in the app.  I have no strong opinions on colour scales other than it will probably take a while to get something everyone is happy.  

It is easy to experiment, here are a few (I've tried adding more than just ranging from two colours but I'm not great at the aesthetics....)
![darkslategrey_cornflowerblue_tan1_yellow](https://cloud.githubusercontent.com/assets/6289830/17536850/09aae724-5e90-11e6-95db-972eb2e127be.png)
![darkslategrey_darkgoldenrod_yellow](https://cloud.githubusercontent.com/assets/6289830/17536849/09aac0a0-5e90-11e6-8dad-b9fb9bdb6b0d.png)
![grey16_cornflowerblue_tan1_yellow](https://cloud.githubusercontent.com/assets/6289830/17536851/09b09156-5e90-11e6-8f06-d2f8edc2f9fa.png)

**Comment by Robinlovelace** [comment]
Nice! Thanks for the experiments. I suggest we post more experimental schemes here. Will try the option of getting a colour scheme up that's consistent with the red:green of the front page, but not before we've got the national build in order.

**Comment by AnnaGoodman1** [comment]
now picked up an issue #374
