### ISSUE TITLE
Lines/zones download sig figures/decimal places policy

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#345]
Minor question, but I wondered what our policy was on sig figures/decimal places for the data downloads (seemed sometimes to be 2 dp and sometimes more). Just as it affects rounding down to zero and so may affect people aggregating lines data for less ambitious scenarios (for instance). I can put something about it in the manual.

**Comment by Robinlovelace** [comment]
We round to 5 sg figures.

Suggested policy: provide as many decimal places as is used internally in R (shows precision of method) but display 2 s.f. for values < 100 (e.g. cirquity, avslope, dist) and 0 s.f. for values > 100 (e.g. ...).

@nikolai-b I think you added this: https://github.com/npct/pct-load/blob/master/build_region.R#L173

Here's a good place to discuss: not sure it's useful.

**Comment by AnnaGoodman1** [comment]
I don't like the idea of altering the number of decimal places according to the size of the number, it would seem odd to have 99.92 but then just 101. I think it is better to choose an appropriate number of decimal places for each variable, and applied that

For the scenario data generated by me, the rule is:
* Cyclists/drivers/walkers in scenarios: two decimal places (used to be three decimal places for the zones, but that is not very consistent - Robin, can you upload the attached replace the existing input CSV file on PCT big data? No need to rebuild the Cambridge/Kent now, but this file can be used in forthcoming builds)
[160809_AreaPCT.zip](https://github.com/npct/pct-shiny/files/408868/160809_AreaPCT.zip)
* Number of deaths: five decimal places in both zones and lines
* value of production in number of deaths: nearest whole number in both zones and lines
* CO2: nearest whole number in both zones and lines

For the geographic data created by R, I suggest an appropriate level of rounding would be
* avslope variables(zones and lines); dist variables; cirquitry/dist_qf; clc: round to two decimal places, rather than the current five decimal places for some and then three decimal places for others.  
* time variables: nearest whole number (this is already correct)

**Comment by Robinlovelace** [comment]
The key thing is the number of s.f. we display. Being faithful to the data is my priority in the data download so I'm against any removal of precision there - hence the discussion.

**Comment by Robinlovelace** [comment]
Can we separate out discussion of what we display (which I think is OK) and what we make available to download (where I think we should not artificially remove s.f.). Awaiting feedback from Nikolai as to why he rounded everything to 5 s.f. - may be a performance issue in which case it makes sense.

**Comment by nikolai-b** [comment]
I set 5 s.f. on the download as without it the CSV and geoJSON were quite big (I think they had up to 13 s.f. which seemed a bit over the top).
From [this](https://github.com/npct/pct-load/blob/8b27e0d/set-up.R#L61) you can see 
we are only simplify them after saving the RDS so the RDS file is not rounded.
I have no strong feelings but it made the files much smaller. Happy to change if you want!

(also I'm happy to talk on Slack but can't on GitHub, sorry)

**Comment by AnnaGoodman1** [comment]
I definitely don't think we should add in more significant figures/decimal places to the geosjon/csv data downloads. (At the moment it looks as if it is actually using 5 decimal places not significant figures, Nikolai? ).  indeed, I would have a preference for reducing it further in geojson / csv to have only two or three decimal places rather than the current five.  Would improve performance further in terms of memory, but also avoids spurious precision - I don't think it is helpful to give percentages or distances to five significant figures, that is much much more accurate than we can say with any confidence and just makes the numbers harder to read - and I think the CSV file in particular is one that people are likely often to open up just to look at.  also looks odd IMO to be giving eg clc to five decimal places when most scenario numbers have at most two decimal places.  But if Robin disagrees then I guess we leave it as it is.  I agree that the display is fine as it currently is

**Comment by Robinlovelace** [comment]
Discussed with @nikolai-b briefly yesterday. Proposed policy: reduce n. decimal places to a minimum for plain text formats (happy to go from 5 to 2 for plain text formats but suggest we leave at 5 to avoid having to rebuild regions already built for consistency). We save the `.Rds` files, which are much more space efficient, before rounding so that that's fine. In summary, we're already doing roughly what makes sense although could further save file and headspace by reducing the n. decimal places further for saving plain text formats. A productive discussion!

**Comment by Robinlovelace** [comment]
Closing for now as no clear action. Suggest if we do want to change our current policy (5 d.p. for text data) we do it asap.
