### ISSUE TITLE
Make the menu on the right moveable

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#38]
It was made static because it moved problematically when the sliders were moved.

But sometimes it's useful to move it - can we do this?

Maybe more useful and easier: allow the user to move the scale bar.

**Comment by usr110** [comment]
@Robinlovelace I've made both the panel and the legend moveable. 
This actually introduced a new bug for the tooltips - they stopped working. So now instead of tooltip logic on the UI, I've moved it on the server side. It seems to be working fine. Also I've further shorten them. See the details here - https://github.com/npct/pct-shiny/commit/76903fc4c6713afc7b244312d2ee66d9c7ea6238
I'd be nice if you and @nikolai-b can test the new changes out.
