### ISSUE TITLE
Update scenarios for v1.1

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#380]
This will use updated hilliness and distance data from CycleStreets.net, to be generated by @mem48, leading to a minor update of the scenario numbers. The plan is to generate the scenario numbers using an updated version of this: https://github.com/npct/pct/blob/c098449f2b35babc57b504cb63d026a98f196208/gm_scenarios/L4aPCT_scenarios.R . And have the entire process done in a single process involving a few scripts located here: https://github.com/npct/pct-load/tree/master/R .

**Comment by AnnaGoodman1** [comment]
Well, lets see, that would be great if feasible to do such that we  can still stick to timeline of starting the national build first week or so of October - otherwise I would vote for using the same process as at present (Ie pct_area/pct_lines generated by me) rather than delay the next national build, and save integrating/tidying up for the next iteration.  But if that work can be done in time then good

**Comment by Robinlovelace** [comment]
And here's a schematic diagram to represent the work to be done from Anna.
[160817_ProcessDiagram-1.pdf](https://github.com/npct/pct-shiny/files/428175/160817_ProcessDiagram-1.pdf)
