### ISSUE TITLE
Front page legend not rendering properly in Chrome

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#399]
While in Firefox making the front page bigger or smaller doesn't affect the legend display, in Chrome it shifts out of line e.g. see below.

![picture1](https://cloud.githubusercontent.com/assets/11818218/18583441/7dd7998c-7c02-11e6-99a5-59380961c9f8.png)

**Comment by nikolai-b** [comment]
It looks like your are zooming the entire page instead of zooming in on the map.  These examples are on Chrome(ium):

Zoomed in map with page at 100% zoom:
![screenshot from 2016-09-30 10-04-00](https://cloud.githubusercontent.com/assets/6289830/18986615/7ffecb60-86f5-11e6-8c3a-af905392444e.png)

Zoomed out map with page at 110% zoom:
![screenshot from 2016-09-30 10-04-13](https://cloud.githubusercontent.com/assets/6289830/18986614/7ffc95f2-86f5-11e6-8a2d-4c978bba4a21.png)
