### ISSUE TITLE
Lines and zones datatable throw an error when moved to a new region

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#419]
![datatable_error](https://cloud.githubusercontent.com/assets/10958628/19119276/2783a426-8b17-11e6-861e-cb85c6af8c6e.png)

**Comment by usr110** [comment]
For some reason the issue hasn't resolved yet. Locally it seems to work fine, but don't know why it's not working on the test server?

**Comment by nikolai-b** [comment]
I've updated `DT` and also installed a new version of Shiny Server.

I'm pretty sure a know what the problem is due to 
https://github.com/npct/pct-shiny/blob/a2b67bdfcdc1f14099efe8a7ab9c497c0cd0a9ff/www/assets/extra.js#L30
where we change the url address.  Looks like this is a problem on production also.

Here is the output from the console
```
jquery.min.js:4 POST http://npct0.vs.mythic-beasts.com/session/b6ad37f7... 404 (Not Found)
```
which looks wrong.  A previous request by datatables was sent to 

```
http://npct0.vs.mythic-beasts.com/greater-manchester/session/b6ad37f7...
```

So it looks like when we change the window location (i.e. [pushState](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method) which we do when moving regions) then shiny get confused seems to be sending the incorrect URL to `POST`s to the site root instead of the new.

The fullstack trace is
```
jquery.min.js:4 POST http://npct0.vs.mythic-beasts.com/session/b16615dd99afb0f717a504e1eaea99ab/dataobj/zones_data_table?w=&nonce=516c9dff5dfa48cc 404 (Not Found)
send @ jquery.min.js:4ajax @ jquery.min.js:4
ra @ VM1574:36
lb @ VM1574:37O @ VM1574:29
T @ VM1574:31
ga @ VM1574:48
(anonymous function) @ VM1574:93
each @ jquery.min.js:2
each @ jquery.min.js:2
m @ VM1574:82
h.fn.DataTable @ VM1574:166
renderValue @ datatables.js:210
shinyBinding.renderValue @ VM1438 htmlwidgets.js:508
onValueChange @ shiny.min.js:3
delegator.(anonymous function) @ VM1438 htmlwidgets.js:112
onValueChange @ shiny.min.js:4
receiveOutput @ shiny.min.js:3
(anonymous function) @ shiny.min.js:3
_sendMessagesToHandlers @ shiny.min.js:3
dispatchMessage @ shiny.min.js:3
c.onmessage @ shiny.min.js:3
_conn.onmessage @ shiny-server-client.min.js:1
MultiplexClient._conn.onmessage @ shiny-server-client.min.js:1
BufferedResendConnection._handleMessage @ shiny-server-client.min.js:1
RobustConnection._handleMessage @ shiny-server-client.min.js:1
conn.(anonymous function) @ shiny-server-client.min.js:2
d.dispatchEvent @ sockjs-0.3.4.min.js:27
y._dispatchMessage @ sockjs-0.3.4.min.js:27
y._didMessage @ sockjs-0.3.4.min.js:27
e.ws.onmessage @ sockjs-0.3.4.min.js:27
```

**Comment by usr110** [comment]
@nikolai-b Thanks for the updates.

**Comment by Robinlovelace** [comment]
Looked like a right hassle to sort out so cheers for that.
