### ISSUE TITLE
something weird in switching commuting vs all trips 

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#448]
it was showing commuting under all trips and all trips under commuting when I played with show lines slider and toggled between layers. then it just disconnected from server.

**Comment by audev** [comment]
I noticed the switching is not 100% reliable, although works fine most of the time. Also, re disconnections, it tends to be more stable in Chrome than in Firefox (this might be just my install).

**Comment by JDWoodcock** [comment]
I tried on chrome. I find I start using it with commuting. I flip to all trips. Nothing happens. I flip back to commuting- all trips appears. Then I flip to all trips- and commuting appears

**Comment by nikolai-b** [comment]
Yep, the radio input is not updating the lines properly.  I plan to fix when we have the national build going.

**Comment by usr110** [comment]
I am still trying to catch up what updates and changes have been made while I was away. After initial investigation, it seems that the lines are plotted first and then the `all-trips` data is loaded, which is wrong. It may be due to the removal of the reactive expression `repopulate_region` at: https://github.com/npct/pct-shiny/commit/3d9086779e8b19ac5fd752ee36554219f03e4564

**Comment by usr110** [comment]
In case anyone wants to have a screenshot of the application, there's a small hack to update the lines. Once you switch from `Commuting` to `All`, you may want to pane around the map. This updates the lines.

**Comment by Robinlovelace** [comment]
Great work Ali, we're getting through the issues at a 'rate of knots'!
