### ISSUE TITLE
Change 'Route Information' popup on screen

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#47]
The amount of clutter on the map should be kept to a minimum and I think the new popup information added by https://github.com/npct/pct-shiny/commit/155d2761c69645184c7d02bb7174f4fb38e8bf0c . @usr110 is there a way to display the information more discretely, in a way that does not consume precious map space? I'm with Nikolai in thinking we need to keep the interface really clean. I would be happy if this were moved into the help.

**Comment by usr110** [comment]
@Robinlovelace I do understand @nikolai-b's point about having as minimum controls as possible, but I believe we've already talked about it. I wouldn't call route popup as invasive, as this panel only shows up when user clicks on it. I've further shrunk its size - see here https://github.com/npct/pct-shiny/commit/b2e0eebd9c0587bcf620cd79744e6507870bfe57. Also, I don't know if you had the chance to the recent changes or not, but now both panel and legend can be minimized. See here: https://github.com/npct/pct-shiny/commit/261b63ce68a6d45813b15b86f7fcca472cfc6ef3. So that already gives more space to the user to focus just on the map.

**Comment by Robinlovelace** [comment]
Hi @usr110 your updates are great and certainly minimise the problem, thanks for that. However, on small screens like my laptop, the default location of the "Route Info" box on the map overlaps with the dropdown menu. I think it's fantastic that the information on the route can be viewed, I just don't think a box that is visible on the main map all the time is the best way forward. Moving the information to the help or ensuring it only appears when routes are actually being displayed would solve the problem. If there are good reasons for making the box visible on the map all the time, please let me know! 
![selection_201](https://cloud.githubusercontent.com/assets/1825120/7715078/62127c08-fe7c-11e4-8398-df8a4432507c.png)

**Comment by Robinlovelace** [comment]
Believe this was closed by @nikolai-b  - pls add sha if you get a chance. Ta
