### ISSUE TITLE
App not working on the test server for any region

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#474]
> Warning: Error in ogrInfo: Cannot open file
Stack trace (innermost first):
    47: ogrInfo
    46: withCallingHandlers
    45: suppressMessages
    44: readOGR
    43: eval
    42: eval
    41: withVisible
    40: source
     1: runApp
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open file
"

**Comment by Robinlovelace** [comment]
Thanks for reporting Ali. I noticed it this morning and suspected it was due to this commit: https://github.com/npct/pct-shiny/commit/cdd031b4d433c89338f5366519a1140c57bfa3c8

But after found some regions worked. Heads up @audev I'll temporarily revert that to see if that helps.

**Comment by Robinlovelace** [comment]
Update - thinking it cannot be a data issue as it affects all regions. Please can you take a look @nikolai-b when you get a moment?

**Comment by Robinlovelace** [comment]
That seems to have fixed it: https://github.com/npct/pct-shiny/commit/8ee9ff1afdc22d29f16672c8b52c5a9c177759b5 

Will check if commits subseqent to that make it break.

**Comment by Robinlovelace** [comment]
Explanation: when @nikolai-b moved regions to pct-data/regions_www/ the place that pct-shiny pointed to get the regions was not updated seemingly.

We were relying on regions.geojson being in two places!

**Comment by usr110** [comment]
Thanks Robin.

**Comment by nikolai-b** [comment]
I moved regions in 60f2b3d over a month ago so it was not anything to do with that.  It was https://github.com/npct/pct-data/commit/d8c05ebeffe671c8314cb8f9c5c6612a70e4607f that caused the app to break.  Please check before you push changes that brake the app @Robinlovelace !

**Comment by Robinlovelace** [comment]
Yes I know that, hence the fix. 

We shouldn't have been using the same version of the same file in the first place.

When you created the new version with https://github.com/npct/pct-shiny/commit/960e30f73eef898843c2283e86e2f506fccb1d05 old version should have been deleted.

Since https://github.com/npct/pct-shiny/commit/8ee9ff1afdc22d29f16672c8b52c5a9c177759b5 we only use one version of regions.geojson which I think you'll agree is an improvement and which I assumed we did in the first place.

https://github.com/npct/pct-shiny/commit/8ee9ff1afdc22d29f16672c8b52c5a9c177759b5 also makes the app more internally consistent by reducing dependencies on pct-data.

Apologies for breaking the app in any case - due to a mis-understanding: I did not know we were using 2 versions of the same file.
