### ISSUE TITLE
Decide url structure

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#504]
Linking to the discussion here: https://github.com/npct/pct-shiny/pull/503

**Comment by mvl22** [comment]
I spend a lot of time thinking about URL structures when I develop. So I hope the following points may be of use in this discussion:

 * I would always avoid URLs containing visible query strings, i.e. containing `?`, except for very trivial things. You can almost always get rid of these using `mod_rewrite` or an internal application equivalent.
 * URLs should always be canonical - there should never be two URLs for the same content. This includes trailing slashes (which should always redirect or be redirected to), use of www/non-www, etc.
 * If a URL like `/cambridgeshire` isn't actually present in terms of links that the system writes out, then it can be regarded as non-existent.
 * URLs should generally be designed to be permanent and designed so that they make complete semantic sense for the long-term even as the application expands. Use `mod_rewrite` or an internal application equivalent to avoid having to tie the URLs to the application code as the latter changes.

**Comment by Robinlovelace** [comment]
Thanks for the input Martin, very useful. Only problem: not 100% sure how that feeds into concrete recommendations. What's so bad about `?` in the url? Agree this is a big decision that we should get right. Does any of this change what your strategy would be @nikolai-b? At the moment we're only discussing the name of the subfolder in https://github.com/npct/pct-shiny/pull/503 but it sounds like you want to broaden the discussion. But I don't see any other easily implementable options on the table.

**Comment by mvl22** [comment]
> I am less sure about the addition of /msoa/ to the URL since we are about to be launching that contains (and can jointly show) a mixture of MSOA and LSOA data - I hadn't appreciated at the last meeting that that addition was also proposed. (if anything the more relevant condition might be something like '/commuting/'

`/msoa/` has exactly the problem that it is very limiting. When you want to mix more data levels than MSOA, you'd need to change it, and bookmarks and links break.

If /msoa/ is currently an approximation for the concept of 'commuting' then the moniker `/commuting/` is a forward-compatible URL that will work as the system expands.

**Comment by mvl22** [comment]
> Can we keep it shorter than commuting please?

While it is strongly sensible to aim for short URLs, needless abbreviations are best avoided as they create unguessability and future vagueness of what they're supposed to be about.

Abbreviations also have the potential to create namespace clashes - see point 4 above.

**Comment by mvl22** [comment]
`/map/?r=avon`
or
`/m/?r=avon`

I would avoid `m` as above - could be many current or future meanings.

Looking at these two URLs, I would first ask what is the important thing here. If the aim is to show data for Avon, the fact this on a map is not the critical thing; it is almost an assumption that a mapping-based site would have maps. There might also be charts, data downloads, etc., in future.

So

`/avon` might be your map view
`/avon/charts` might be a future chart view.

**Comment by mvl22** [comment]
> I think region urls like http://pct.bike/cambridgeshire should still work - is it the plan @nikolai-b to redirect that to http://pct.bike/msoa/?r=cambridgeshire ?

Imagine if you were a Council person you were promoting the system to on the phone, and asked them to type each of these two examples into their browser. Only the first is likely to succeed, I would suggest.

**Comment by mvl22** [comment]
> 'http://pct.bike/england/?r=avon' or 'http://pct.bike/uk/?r=avon'

> I'm not a fan of uk because we don't have the UK in there yet (e.g. Scotland, Northern Ireland)

I don't think a temporary lack of data for an area of the UK should be a blocker for using `/uk/`, as the intention is filling-in the missing bits.

The more difficult issue is whether you actually want a country namespace at all. `/birmingham/` is a nice, memorable URL. However, it will be problematic when you cover Alabama in the USA :)

This question is basically one of whether you see the system as gradually becoming international, or whether you think governments in an individual country will want their own installation.

**Comment by mvl22** [comment]
> I'm not a fan ok uk because we don't have the UK in there yet (e.g. Scotland, Northern Ireland). I'd prefer m or any other letter of the alphabet, it doesn't have to mean anything, look at amazon's URL for kindle products e.g.
> https://www.amazon.com/b/ref=br_pdt_mgUpt/151-1225585-6231519?_encoding=UTF8&node=6669702011&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=BJQ4YMJW8AKF7XFW05RN&pf_rd_t=36701&pf_rd_p=9974eadb-3306-415d-bd0b-c251318255d0&pf_rd_i=desktop
> it starts with a /b/

Amazon URLs are terrible and in no way best practice.

* `/b/` is just meaningless lengthening, and probably some kind of technology-related thing.
* Most of those parameters are irrelevant and can be removed
* For SEO purposes, the word 'Kindle' isn't even present.
* I bet that URL caches badly at server level.

**Comment by mvl22** [comment]
> Ah, I didn't realise m was map rather than short for msoa!

This is a good example of the namespace collision issue - `m` could validly mean either and would remove future flexibility.

**Comment by mvl22** [comment]
> Redirection means that it won't be visible to users, so I don't think that's useful. It will only work as compatibility for those who've saved the old URLs.

I agree - redirection means that people have to have special legacy knowledge about what used to exist, so in practice might as well not be there.

**Comment by mvl22** [comment]
> Now that nikolai-b has explained to me on slack why we need an additional folder (such as eng), I am happy with any solution - whether it's m or eng or whatever is decided.

I haven't seen that discussion obviously, but I would start from the perspective of designing a meaningful URL, then adjust the technology to it. Stuff like `mod_rewrite` enables you to do this fairly easily.

For instance, over the last 18 months, vast amounts of code have been moved around CycleStreets, adjusting all the code to a proper MVC infrastructure (to facilitate our redesign work) but URLs have been completely unchanged.

**Comment by mvl22** [comment]
Hope these are all useful comments and come across as constructive!

**Comment by nikolai-b** [comment]
I agree with the points but we aren't using Apache so `mod_rewrite` isn't an option.  Also the point is the map moves the URL so your points about query string is to allow the user to move around then share the URL.

Look at https://www.google.co.uk/maps/@54.0854536,-1.3968959,13z for example, you see what I see.

Now if I go to https://www.cyclestreets.net/ and move the map around I can't share that link.  With PCT the URL changes allows the link to be partially shared (albeit not the select options but at least the region).  Changing only the query string is a safe way of doing this. 

My point against `uk` is that we are funded by the DfT with a specific remit and I would not like us to use URLs that extend (or limit) that remit.

The index / home page is at `www.pct.bike` so to let shiny server know we want to point to the shiny map we need a subdomain. I'd much prefer to use something like `m` or and other single character as this is more an issue with shiny server instead of a way of communicating to site users.
