### ISSUE TITLE
Allow users to confirm before region change

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#535]
Currently the region jumps when you scroll out of the current region on the map. This is not documented and can surprise the user.

Therefore, as discussed with @JDWoodcock, @AnnaGoodman1, @RachelAldred and other team members, we should change this (additional reasons: it becomes erratic at low zoom levels, when zoomed out and is **currently broken for the largest region: London**).

Mission:

- [ ] Add the regions layer to the map beyond a certain zoom level, I suggest level 10 as it's allows you to see the majority of a big region as illustrated below (1hr):

![image](https://cloud.githubusercontent.com/assets/1825120/23548928/b41b8214-0001-11e7-8caf-3ff710d9b852.png)

- [ ] Create add the url popups to the regions, link in the front page map (30 min)
- [ ] Deploy on test server and send round to team (30 min)

Estimate of number of hours: 2 - reasonable @nikolai-b ?

**Comment by nikolai-b** [comment]
I think this is best described as an issue instead of what you think needs to happen so I see the problem but I think the solution is not the mission you've described, I'll get something up on a branch so you can review.  I think 2 hours might be ok but possibly a bit more.  P.S. it works for London as you requested #238 or were you describing something else.
