### ISSUE TITLE
Top panel has changed, looks strange

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#54]
Any ideas @usr110?

![selection_243](https://cloud.githubusercontent.com/assets/1825120/8061259/f4b5626e-0ec1-11e5-97e5-354609c1b1fa.png)

**Comment by usr110** [comment]
I guess it's to do with the introduction of the model-output file. May be @nikolai-b would have better ideas. I made a quick (and dirty) fix so that the data tabs fit fine according to the screen's width. Let me know if this works - https://github.com/npct/pct-shiny/commit/76112154a022020e639e552a3251efb97a016ef6
