### ISSUE TITLE
Set the centre of the map to the loaded region

### ISSUE THREAD

**Issue by usr110** [npct/pct-shiny#543]
As discussed here:

https://github.com/npct/pct-shiny/pull/539#issuecomment-284361301

**Comment by usr110** [comment]
@AnnaGoodman1 and @JDWoodcock would appreciate if you could test the new functionality on the test server. If it is unhelpful, please let me know; I will remove it.

**Comment by JDWoodcock** [comment]
I am finding it a bit jumpy- sometimes clicking doesn't work- not always sure what is going to happen

**Comment by Robinlovelace** [comment]
I find this unhelpful.

Typical first user experience - "let's zoom in on my home" (Otley in this case):

![image](https://cloud.githubusercontent.com/assets/1825120/23618188/71816e68-0287-11e7-8e9c-664f53502ebf.png)

"Woo what happens when I click on that blue thing?"

...

![image](https://cloud.githubusercontent.com/assets/1825120/23618222/96a0f15a-0287-11e7-9689-3e444f2de9ba.png)


Woa now, where am I??!!

The behaviour was better before in that use case: it would show the data is there but the user would easily be able to switch back to their MSOA of choice.

**Comment by usr110** [comment]
Minor corrections and bug fixes in: https://github.com/npct/pct-shiny/commit/391a36cdd42e1c4ec0c4771c1bd6d4d6bf6b81f8. Please try again in a bit.

**Comment by Robinlovelace** [comment]
Just tried again - still the same behaviour - confusing - when you click on it when zoomed in. When zoomed out I find it more useful to be able to click on multiple places without some unknown force moving your map around. Happy to hear what other people think and listen to the arguments in favour of this suggested change.

**Comment by Robinlovelace** [comment]
P.s. what is the issue, thing that is wrong, that this fixes? The title of the issue is a task, not an agreed problem that should be solved. I suggest renaming to reflect the issue that is being fixed (that the map does not move presumably, although I don't see that as an issue and wouldn't expect a map to move when it was clicked on - think of Google Maps for example).

**Comment by JDWoodcock** [comment]
can we see it in conjunction with LSOA layer as that is where this is likely to come up most

**Comment by usr110** [comment]
James, done in: https://github.com/npct/pct-shiny/commit/bb9206cda6c37b3a9709b27c6144f28862cefa32. You may try again.

**Comment by usr110** [comment]
Have reverted the commits. Was buggy and perhaps slowing down the application. Please @AnnaGoodman1 don't test the feature, if you plan to. It's not there any more. Thanks for testing everyone.

**Comment by Robinlovelace** [comment]
Thanks for reverting.

Behaviour now: 

"Here I am in my home village, what happens if I click there:"

![image](https://cloud.githubusercontent.com/assets/1825120/23648460/b394aae6-0312-11e7-9a43-d7c0489c0373.png)

Wow there's data for all regions - awesome!

![image](https://cloud.githubusercontent.com/assets/1825120/23648486/d3e12540-0312-11e7-80a8-435ea09be665.png)


This is much better.

Good example of agile testing and being adaptive - think there could have been more prior discussion in this case but great to test it out to see what it was like.
