### ISSUE TITLE
warning banner on test server - add to near market?

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#568]
If not a lot of work, would be good to have the nice warning banner on the main test server also added to the nearmarket link http://npct0.vs.mythic-beasts.com/nearmkt/?r=greater-manchester  since we are sharing that with a limited number of people. this is not very urgent. Thanks!

**Comment by usr110** [comment]
Have added the banner using Nikolai's commits: https://github.com/npct/pct-shiny/commit/3e468f21fbb18888e4ac1608ac8f217c521314cb and https://github.com/npct/pct-shiny/commit/b7b9464855c0da386810524f8df2f5b9df449181
Also added `robots.txt` (again from Nikolai's commit: https://github.com/npct/pct-shiny/commit/49f4a1c57a392a6c5b257e131c112ba9c6130940), so that it remains private
