### ISSUE TITLE
Regenerate vector route network layer

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#584]
Should be an improvement in various ways, and include inter-regional flows.

**Comment by AnnaGoodman1** [comment]
Yes, before you do all of them it might be worth doing it just for e.g. Cambridge and we can all agree we are happy with the new method?  E.g. I'm assuming you will include cross regional flows in the route network layer but We might want to have a discussion as to whether it then gets clipped at the boundaries or  the lines continue to their full extent. ( I would probably favour clipping it at the boundaries, so that one can piece together multiple route networks But I'm not sure on this).

**Comment by Robinlovelace** [comment]
Yes I will send an example for a single region before building for all regions.

**Comment by Robinlovelace** [comment]
I also plan to update the visualisation, in response to the impressive colour scheme created by @mem48 in collaboration with others.

**Comment by AnnaGoodman1** [comment]
can close this now @Robinlovelace ?

**Comment by Robinlovelace** [comment]
Yes, well spotted. We, or rather @mem48 + my big computer, have aced it!
