### ISSUE TITLE
pct wales refreshing

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#597]
the zones refresh (moving between scenarios) when one moves around. At one point it got into a loop.

![image](https://user-images.githubusercontent.com/11028720/29714736-58c75440-899c-11e7-8960-5ff5bbb38489.png)

I am using firefox.

**Comment by AnnaGoodman1** [comment]
this is my fault, I had not incorporated what we had in the code previously of isolating the map zoom, so that the zones did not automatically refresh when changing zoom.  I think I have now fixed this on the master branch here https://github.com/npct/pct-shiny/pull/596/commits/73a5af2bb1eb4e8d45413aa8d7109f9566635b95

(not sure if this will solve the problem of getting into a loop or not, didn't know how to replicate that)

**Comment by Robinlovelace** [comment]
I've tested this on my laptop and it worked (after fixing a strange issues with readOGR that I'll fix in the master branch). Seems not to refresh the zones or other objects now so closing. Thanks for reporting + fixing this!

![image](https://user-images.githubusercontent.com/1825120/29780020-35c77e4e-8c0c-11e7-8ab9-459dcac9a6f4.png)
