### ISSUE TITLE
csv download bug in firefox

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#621]
in the course of adding csv downloads the zones, I notice that the CSV download function was already not working well for the existing 'all flows' csv files (or the new csv zones files) on Firefox browsers. Microsoft edge and Google Chrome give one a CSV download if you click the link, but Firefox opens the CSV in a new page
![untitled](https://user-images.githubusercontent.com/11818225/30325723-b07299fa-97bd-11e7-9d7d-56f9cec308de.png)

this does not happen for the codebooks because they are using cdn.rawgit, just the lfs files... And one can then right click the Firefox page to "save page", at which point it saves as csv.  But obviously nicer if it did this all in one go

Any ideas on this, anyone?

**Comment by Robinlovelace** [comment]
I don't think this is a bug. It's a browser issue. If you press `Ctl-S` it should save it as a .csv file. I think mentioning that in the manual should be sufficient to close this issue.

**Comment by AnnaGoodman1** [comment]
I agree that is def an option, but I guess will still annoy/puzzle some users. Lets see if @nikolai-b / @usr110 have any thoughts on how to make firefox handle this download differently - if not then I agree we can live with it.

**Comment by nikolai-b** [comment]
This is a bug!

The browser deals with different content based on the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type and git hub (purposely) doesn't set the content type header.

**Comment by nikolai-b** [comment]
Sadly I think the answer would be to use S3 as github isn't the correct place to serve files.

**Comment by AnnaGoodman1** [comment]
Thanks @nikolai-b... that is a bit of a pain, but perhaps  (not urgent) is worth transitioning to S3 in that case. in which case, sorry, I was wrong to talk you out of it before... 

if we did this then I would suggest that pct-outputs-national and pct-outputs-regional-notR would be deleted from git and moved to Amazon S3.  (ideally, for consistency, we might move pct-outputs-regional-R to S3 too - but I think perhaps that needs to be on git for cloning to the server?).  these repos are in any case much too big to readily clone on git.  Would that seem okay to you @Robinlovelace ? 

or the alternative is that we leave it as it is and live with it – we could ask James and Rachel how much of a problem they think it is at the next team meeting

**Comment by Robinlovelace** [comment]
My preference is to not switch it after the considerable amount of time setting all this up on GitHub and recloning it all to everyone's computer etc. Also based on a preliminary reading of this thread I suspect it would be possible to make Firefox open it as a download with a bit of JavaScript: https://github.com/mholt/PapaParse/issues/175

**Comment by nikolai-b** [comment]
Interesting @Robinlovelace , I believe that solution would require the CSV's (and GeoJSONs) to be downloaded onto the client if they were clicked or not (it starts with getting `csvString`), which is is impractical.

Considering the browser does not try to download the R files these could remain on GitHub (in FF they do open a new page but they then download the Rds as a file) it is the CSV and GeoJSON that look really bad.  For consistency S3 would be better though.

@Robinlovelace is your worry that `pct-outputs-national` used to generate the regional data? We can then just have one version on S3 and use https://github.com/cloudyr/aws.s3/blob/master/man/sync.Rd to keep our the local copy up-to date.
I could set up cloning using the AWS CLI on the server, it is definitely a medium sized piece of work but GitHub is not designed to be the place to store large files for many of the reasons we have encountered. Then again the issue is only for FF users so it isn't top priority.

**Comment by Robinlovelace** [comment]
It sounds like a question of weighing up the benefits of consistency and the time invested in the current system against potential benefits of someone running FF seeing a pop-up like that shown below for the .csv files. I think development time is better spent fixing more serious bugs, as and when they arise rather than this relatively minor usability issue.

![image](https://user-images.githubusercontent.com/1825120/30397364-8d9aea38-98c4-11e7-8ba7-bda6dd6cd09d.png)

**Comment by Robinlovelace** [comment]
Update: just tested the behaviour with .geojson files and it seems to go to open the download popup, as shown below.

![image](https://user-images.githubusercontent.com/1825120/30397740-bf7bb662-98c5-11e7-8046-58229d84f55f.png)

**Comment by nikolai-b** [comment]
It is a minor bug, I was just suggesting a way to fix it.
If this is more effort than we think is worth it then it makes sense to close as won't fix.

GitHub is not the best place to store and serve large data files but that alone isn't enough to warrant moving elsewhere, just worth bearing in mind if we make changes in the future.

**Comment by Robinlovelace** [comment]
Thank Nikolai. @AnnaGoodman1 are you happy for this this to be closed for now? I've tagged it as for the future so we can easily find, reopen and properly fix it later down the line if needs be.

**Comment by AnnaGoodman1** [comment]
yes, agreed, lets close for now.  I  have added some warning text for users here https://github.com/npct/pct-shiny/pull/631 (I think should be here not in manual to help people see it...as it would confuse me otherwise)

**Comment by Robinlovelace** [comment]
Great stuff Anna. Minor point but if we had version control on the manual (e.g. as a html/md/Rmd doc) we'd be able to do that via this system also and others would be able to contribute. Cc @RachelAldred on that - could encourage the 'wiki' and open collaboration aspect of this, especially for people who aren't R programmers ; )
