### ISSUE TITLE
Problems with LSOA route network rasters for some English regions

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#649]
Hi all, at the recent training some of the LSOA route network rasters (e.g. for Liverpool City Region) wouldn't download and/or open, while others would. The ones that didn't work either wouldn't download full stop, or downloaded but then QGIS was unable to open them, describing them as an unsupported file.

Ones that are working (e.g. Isle of Wight) seem fine.

**Comment by Robinlovelace** [comment]
Interesting - not come across that issue before but then again I've not used the regional rasters much. Could you provide a reproducible example explaining the steps taken? That will help resolve the issue fast. Many thanks for reporting in any case and will be one for me to watch-out for down in Portsmouth.

**Comment by RachelAldred** [comment]
Hi Robin
Sure, go to Liverpool City Region and try and download any of the LSOA raster TIFs. If it downloads, then try and open it in QGIS.
Is that enough detail? Hopefully we resolve it well before Portsmouth.
Thanks
Rachel

**Comment by usr110** [comment]
Thanks Rachel. Just checked. It is indeed not working.
I am guessing this is a GitHub issue, as you can't even download a raw file such as: https://github.com/npct/pct-outputs-regional-notR/blob/master/commute/lsoa/liverpool-city-region/ras_bicycle.tif

This gives an `This media.githubusercontent.com page can’t be found` error

**Comment by Robinlovelace** [comment]
Could it be due to GitHub limiting bandwidth? Anna and I discussed this and we agreed to increase the bandwidth temporarily but I'm wondering if that is a long-term solution... I'm not getting the 'page cannot be found' message but also it's not giving me the data...

**Comment by RachelAldred** [comment]
Strange then that London works which I'd have thought would be one of the biggest files?

**Comment by Robinlovelace** [comment]
That's useful information. Some of the files seemed not to work - as stated here (from previous exchange with @AnnaGoodman1): 

> On a related note, I'm in the process of updating my npct repos on my work desktop and came into a tricky issue with lfs that is documented here: https://github.com/git-lfs/git-lfs/issues/911

> Have you come across such 'smudge filter' related issues? It happened multiple times and I managed to resolve it using advice in that previous link.

**Comment by usr110** [comment]
> Could it be due to GitHub limiting bandwidth? 

My impression is that the GH's own servers are not working. Don't think it's related to how much bandwidth is already being used.

>  I'm not getting the 'page cannot be found

This error doesn't appear in Firefox (I am assuming you are using it). May be try using another browser.

**Comment by Robinlovelace** [comment]
"Seem not to work when downloading using lfs" I meant. I don't recall which files are not working but if some files are downloading are others are not we should find out why - may be worth contacting support at GitHub, in my experience they're helpful.

**Comment by AnnaGoodman1** [comment]
Oh dear, sorry, possibly I did this? I updated the regions near wales 12 days ago, hence maybe why some like London work and some like Liverpool not...I am at a conference but will check this on weds and see if I can work anything out. Sorry all...

**Comment by AnnaGoodman1** [comment]
sorry, yes, this does seem to have been a problem that got introduced when I updated these files a couple of weeks ago – I updated the rasters for Wales and the six adjoining regions, and for some reason the files seem to have failed to upload properly on git for Liverpool and Cheshire (while working for the other regions). They looked as if they were on the system, but as Ali said git couldn't actually find them.  

I have now replaced the files for Liverpool and Cheshire, and they seem to work - @RachelAldred , let me know if you think there were other regions they didn't work for (if so then they have probably not been working since last September).

I am not sure why git failed just for these 2 of the 7 regions that got updated.  My best guess is that it may be because I had initially forgotten to increase our amount of git storage when uploaded these files, and temporarily went over the limit. But if a wider number of regions aren’t working then it must be some other problem

Sorry to have disrupted your training with this, Rachel, I hope it wasn't too much of a problem

**Comment by RachelAldred** [comment]
Thanks Anna :) I checked a couple and they looked good. I will let the stakeholders know too so they can test if they want.

**Comment by nikolai-b** [comment]
Thanks @AnnaGoodman1 
This makes me a worried about our system as it should have really given you a warning or failed to accept your changes instead of accepting the change then not working (for some reason).  Really glad it was caught and fixed quickly.
