### ISSUE TITLE
School location accuracy - data precision

### ISSUE THREAD

**Issue by layik** [npct/pct-shiny#699]
Hey guys, congratulations on the release of the school trips/layer.

Just wanted to record the issue of at least one school being positioned slightly away from its real location. It is probably coming from upstream. It is important to know if this affects the "routing"s as we know the model is based on length/distance to origins/destinations. Otherwise worth being aware of it and maybe adding a "tiny" notification.

This is Coop Oakwood Academy (or Oakwood Primary Academy). The curved building on corner of Oak Tree Drive and North Farm Road is where the school is. Unless this is the only case.

![image](https://user-images.githubusercontent.com/408568/54537893-303b8680-498b-11e9-8d2d-34b13be2cae3.png)

I thought I should report it.

**Comment by Robinlovelace** [comment]
Thanks for reporting, and good local knowledge! Do you know if the school has moved in the last 7 years? If so that could explain it. If not, the 'upstream' data from DfT may not be as accurate as we expected (I assumed there were within 100m, but this seems to be more like 200 m out).

In terms of the conclusions drawn, I suspect that changing the school location by even this much would not affect the route networks. And I think other schools are more accurately located (source: local knowledge of a few schools compared with the map). 

Useful to know in any case and it could be handy to know about any other schools that are misplaced. If you, or anyone else find them, please let us know, although we cannot promise to fix this in the app.

**Comment by layik** [comment]
That might actually be the case, the case. Will ask a bit more about that school.
