### ISSUE TITLE
Tunbridge Wells case study title

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#700]
Can we change, on the case study page, 'Tunbridge' to 'Tunbridge Wells'? Someone from the town has pointed out the title is incorrect (there is a nearby town called Tonbridge but Tunbridge has a Wells after it!) Thanks :)

**Comment by usr110** [comment]
@RachelAldred thanks for raising it. This has been sorted for the test-server. I have pushed the same changes to the live-server, but they don't seem to appear.

@nikolai-b it's been a while since I merged the `master` to `production` branch. Recently I closed this issue and pushed (using cherry-picking) those commits onto the `production` branch (see the latest two commits here: https://github.com/npct/pct-shiny/commits/production), but somehow they don't seem to update the live-server. Am I missing some step here?
