### ISSUE TITLE
Lines do not change when moving map

### ISSUE THREAD

**Issue by nikolai-b** [npct/pct-shiny#797]
17350b3 stopped the lines being redrawn when the map moves.

**Comment by Robinlovelace** [comment]
Will test on old and new versions. Well spotted.

**Comment by Robinlovelace** [comment]
![Peek 2019-09-15 13-26](https://user-images.githubusercontent.com/1825120/64921539-7c417980-d7bc-11e9-94de-0b58f016f470.gif)


Fixed in #798 for sure, tested for quiet and fastest routes now, although it didn't seem to want to show lines to the westerly zone in the Isle of Wight. Great fix in any case @nikolai-b by the looks of it.
