### ISSUE TITLE
Test server not auto updating

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#888]
As described in #884. Heads-up @nikolai-b I think this is in your court, happy to look into it though. First priority: diagnose the underlying cause.

**Comment by Robinlovelace** [comment]
To verify this navigate to http://npct0.vs.mythic-beasts.com/m/?r=isle-of-wight and click on the IMD basemap which is now updated in the main website.

**Comment by nikolai-b** [comment]
After the new debain install the server was missing `rsync` as can be seen in the [build log](https://app.circleci.com/pipelines/github/npct/pct-shiny/134/workflows/12c91a43-1b07-42dd-80c5-3e1e457092bb/jobs/1533/parallel-runs/0/steps/0-102)

```
remote: /home/git/bin/update-server: line 11: rsync: command not found
```


I've also added some more Bash script safety so scripts with errors will exit with an error instead of carrying on.  It might cause a deploy to fail as something is missing but it will be much clearer that it is broken instead of being marked as a green build but actually having an error.
